image: ubuntu:20.04

linux-build:
  tags:
    - linux 
  stage: build
  variables:
    PCLSRCDIR: "$CI_PROJECT_DIR/src"
    PCLINCDIR: "$CI_PROJECT_DIR/include"
    PCLLIBDIR64: "$CI_BUILDS_DIR/lib"
    PCLBINDIR64: "$CI_BUILDS_DIR/bin"
    INDIGODIR: "$CI_BUILDS_DIR/indigo"
  before_script:
    - mkdir $PCLLIBDIR64 && mkdir $PCLBINDIR64
    - apt-get update
    - echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
    - apt-get --assume-yes install build-essential autoconf autotools-dev libtool cmake libudev-dev libavahi-compat-libdnssd-dev libusb-1.0-0-dev fxload libcurl4-gnutls-dev libgphoto2-dev libz-dev git curl bsdmainutils
    - cd $CI_BUILDS_DIR && git clone https://github.com/indigo-astronomy/indigo.git
    - apt --assume-yes install nvidia-cuda-toolkit
 
  script:
    - cd $PCLSRCDIR/pcl/linux/g++ && make all
    - cd $PCLSRCDIR/3rdparty/RFC6234/linux/g++ && make all
    - cd $PCLSRCDIR/3rdparty/lz4/linux/g++ && make all
    - cd $PCLSRCDIR/3rdparty/cminpack/linux/g++ && make all
    - cd $PCLSRCDIR/3rdparty/zlib/linux/g++ && make all
    - cd $PCLSRCDIR/3rdparty/lcms/linux/g++ && make all
    - cd $INDIGODIR && make  all
    - cd $PCLSRCDIR/modules/processes/contrib/kkretzschmar/INDIClient/linux/g++ && make all
    
windows-build:
  tags:
    - windows 
  stage: build
  before_script:
    - cd $env:CI_BUILDS_DIR 
    - git clone https://github.com/indigo-astronomy/indigo.git
  script:
    - cd $env:CI_PROJECT_DIR 
    - powershell -File windows-build.ps1




